'use strict';
const $=id=>document.getElementById(id),{moves,combos,pool,choose,Clock}=Tyson;
const clock=new Clock();let cfg,lastId='',count=0,nextAt=0,speechBusy=false,speechToken=0,startedAt=0,workMs=0,previousTick=0,wake=null,audio=null,lastCombo=null;
const synth=window.speechSynthesis;let available=[];
const fields=['level','focus','work','rest','rounds','prepare','stance','gap','pitch','rate'];
function readStore(k,f){try{return JSON.parse(localStorage.getItem(k))??f;}catch{return f;}}
function store(k,v){try{localStorage.setItem(k,JSON.stringify(v));}catch{$('audioNote').textContent='El navegador no permite guardar datos. La sesión sí funciona.';}}
const saved=readStore('tyson-settings',{});if(!readStore('tyson-audio-v3',false)){saved.gap='2';saved.pitch='1';saved.rate='1';store('tyson-audio-v3',true);}fields.forEach(k=>{if(saved[k]!==undefined)$(k).value=saved[k];});
function format(ms){const s=Math.ceil(Math.max(0,ms)/1000);return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0');}
function config(){return {level:+$('level').value,focus:$('focus').value,work:+$('work').value,rest:+$('rest').value,rounds:+$('rounds').value,prepare:+$('prepare').value,stance:$('stance').value,gap:+$('gap').value};}
function label(code){let s=moves[code][0];const south=(cfg||config()).stance==='southpaw';return s.replace('adelantado',south?'derecho':'izquierdo').replace('atrasado',south?'izquierdo':'derecho');}
function refresh(){const c=config();$('gapValue').textContent=c.gap+' s';$('total').textContent=format((c.prepare+c.work*c.rounds+c.rest*(c.rounds-1))*1000);if(clock.state==='idle'){$('timer').textContent=format(c.work*1000);$('round').textContent=`ROUND 01 / ${String(c.rounds).padStart(2,'0')}`;}const p=pool(c.level,c.focus);$('catalogCount').textContent=`${p.length} secuencias disponibles para este nivel y enfoque; ${combos.length} en la biblioteca completa.`;$('catalog').replaceChildren(...p.map(c=>{let a=document.createElement('article');a.textContent=c.id+' · '+c.steps.map(s=>moves[s][0]).join(' → ');return a;}));store('tyson-settings',Object.fromEntries(fields.map(k=>[k,$(k).value])));}
fields.forEach(k=>$(k).addEventListener('input',refresh));$('settings').addEventListener('submit',e=>e.preventDefault());
function voices(){if(!synth){$('voices').innerHTML='<option>Voz no disponible</option>';$('voice').checked=false;$('voice').disabled=true;$('testVoice').disabled=true;$('audioNote').textContent='Este navegador no ofrece síntesis de voz. Usa Chrome, Edge o Safari con voces en español.';return;}const current=$('voices').value;available=synth.getVoices().filter(v=>/^es([-_]|$)/i.test(v.lang));$('voices').replaceChildren(...available.map(v=>{const o=document.createElement('option');o.value=v.voiceURI;o.textContent=v.name+' · '+v.lang;return o;}));if(!available.length){const o=document.createElement('option');o.value='';o.textContent='Español automático';$('voices').append(o);$('audioNote').textContent='Si no escuchas español, instala una voz en español en los ajustes de tu dispositivo.';}if(available.some(v=>v.voiceURI===current))$('voices').value=current;else if(available.length){const rank=v=>/natural|enhanced|premium|neural/i.test(v.name)?100:/google/i.test(v.name)?80:/paulina|mónica|monica|jorge|diego|juan/i.test(v.name)?60:20;const best=[...available].sort((a,b)=>rank(b)-rank(a))[0];$('voices').value=best.voiceURI;}}
voices();if(synth)synth.addEventListener('voiceschanged',voices);
function cancelVoice(){speechToken++;speechBusy=false;if(synth)synth.cancel();document.body.classList.remove('coach-speaking');window.TysonMusic?.voiceEnd();}
function speak(text,done=()=>{}){cancelVoice();if(!$('voice').checked||!synth){done();return;}const token=speechToken;const u=new SpeechSynthesisUtterance(text.replace(/\bjab\b/gi,'yab'));u.lang='es-CO';u.voice=available.find(v=>v.voiceURI===$('voices').value)||null;u.pitch=+$('pitch').value;u.rate=+$('rate').value;u.volume=1;speechBusy=true;document.body.classList.add('coach-speaking');window.TysonMusic?.voiceStart();let finished=false;const end=()=>{if(finished||token!==speechToken)return;finished=true;speechBusy=false;document.body.classList.remove('coach-speaking');window.TysonMusic?.voiceEnd();done();};u.onend=end;u.onerror=()=>{$('voiceStatus').textContent='VOZ NO DISPONIBLE · SIGUE LA PANTALLA';end();};synth.speak(u);setTimeout(()=>{if(token===speechToken&&!finished){synth.cancel();end();}},Math.max(12000,text.length*180));}
function initAudio(){try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();audio.resume();}catch{}}
function bell(){if(!$('bell').checked||!audio)return;for(const [i,f]of [660,880,1320].entries()){const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(.14/(i+1),audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+1.2);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+1.3);}}
async function keepAwake(){try{if('wakeLock'in navigator)wake=await navigator.wakeLock.request('screen');}catch{}}
function release(){if(wake){wake.release().catch(()=>{});wake=null;}}
function showCombo(c){$('sequence').replaceChildren(...c.steps.map(s=>{let el=document.createElement('div');el.className='move '+moves[s][2];const b=document.createElement('b');b.textContent=s;const t=document.createElement('span');t.textContent=label(s);el.append(b,t);return el;}));$('comboLabel').textContent='ESCUCHA Y EJECUTA · '+c.id;$('cue').textContent=moves[c.steps.at(-1)][1];}
function issue(){if(clock.state!=='work')return;lastCombo=choose(cfg.level,cfg.focus,lastId);lastId=lastCombo.id;count++;showCombo(lastCombo);$('counter').textContent=String(count).padStart(2,'0')+' COMBOS';nextAt=Infinity;const text=lastCombo.steps.map(label).join('. ')+'.';speak(text,()=>{if(clock.state==='work')nextAt=performance.now()+cfg.gap*1000;});}
function message(head,cue){$('sequence').replaceChildren();const s=document.createElement('span');s.className='ready-word';s.textContent=head;$('sequence').append(s);$('cue').textContent=cue;}
function stage(){const state=clock.state;document.body.dataset.state=state;bell();if(state==='work'){$('phase').textContent='A TRABAJAR';nextAt=Infinity;speak('Round '+clock.round+'. Manos arriba.',()=>{nextAt=performance.now()+650;});}else if(state==='rest'){$('phase').textContent='RECUPERA';message('RESPIRA. REINICIA.','Relaja los hombros. Recupera el aire para el próximo round.');$('comboLabel').textContent='DESCANSO';speak('Descanso. Respira y relaja los hombros.');}else if(state==='done'){finish(true);return;}$('round').textContent=`ROUND ${String(clock.round).padStart(2,'0')} / ${String(cfg.rounds).padStart(2,'0')}`;}
function pause(reason){if(['idle','paused','done'].includes(clock.state))return;clock.pause(performance.now());cancelVoice();$('start').innerHTML='CONTINUAR <span>▶</span>';$('phase').textContent='EN PAUSA';$('cue').textContent=reason||'Tómate un respiro. Continúa cuando estés listo.';document.body.dataset.state='paused';$('skip').disabled=true;release();}
$('start').onclick=()=>{initAudio();if(clock.state==='paused'){clock.resume(performance.now());previousTick=performance.now();document.body.dataset.state=clock.state;$('phase').textContent=clock.state==='work'?'A TRABAJAR':clock.state==='rest'?'RECUPERA':'PREPÁRATE';$('start').innerHTML='PAUSAR <span>Ⅱ</span>';$('skip').disabled=clock.state!=='work';keepAwake();nextAt=Infinity;speak('Continuamos. Manos arriba.',()=>{nextAt=performance.now()+600;});return;}if(!['idle','done'].includes(clock.state)){pause();return;}if(!$('settings').checkValidity()){$('settingsSheet').showModal();$('settings').reportValidity();return;}cfg=config();lastId='';lastCombo=null;count=0;workMs=0;startedAt=Date.now();previousTick=performance.now();clock.start(cfg,previousTick);$('config').disabled=true;$('counter').textContent='00 COMBOS';$('stop').disabled=false;$('testVoice').disabled=true;$('start').innerHTML='PAUSAR <span>Ⅱ</span>';$('phase').textContent='PREPÁRATE';$('comboLabel').textContent='EMPEZAMOS EN UN MOMENTO';message('EN TU ESQUINA.','Pies firmes, mentón abajo y manos arriba.');document.body.dataset.state='prepare';keepAwake();speak('Vamos a entrenar. Respira, suelta los hombros y sube la guardia.');};
function finish(complete){cancelVoice();release();const phase=clock.state==='paused'?clock.previous:clock.state;const completed=complete?cfg.rounds:Math.max(0,clock.round-(phase==='rest'?0:1));const hist=readStore('tyson-history',[]);hist.unshift({date:startedAt,rounds:completed,planned:cfg.rounds,combos:count,work:Math.round(workMs/1000),complete,level:cfg.level});store('tyson-history',hist.slice(0,30));clock.state='done';$('phase').textContent=complete?'SESIÓN COMPLETA':'SESIÓN FINALIZADA';message(complete?'BUEN TRABAJO.':'HASTA EL PRÓXIMO ROUND.',`${count} combinaciones indicadas · ${completed} de ${cfg.rounds} rounds completados.`);$('comboLabel').textContent='ENTRENAMIENTO GUARDADO';$('timer').textContent='00:00';$('start').innerHTML='OTRA SESIÓN <span>▶</span>';$('config').disabled=false;$('stop').disabled=true;$('skip').disabled=true;$('testVoice').disabled=!synth;document.body.dataset.state='done';renderHistory();if(complete)speak('Sesión completa. Buen trabajo.');}
$('stop').onclick=()=>finish(false);$('skip').onclick=()=>{cancelVoice();issue();};$('voice').onchange=()=>{cancelVoice();if(clock.state==='work')nextAt=performance.now()+1000;$('voiceStatus').textContent=$('voice').checked?'ENTRENADOR POR VOZ':'MODO VISUAL';};$('testVoice').onclick=()=>{initAudio();speak('Vamos. Manos arriba. Jab. Recto. Gancho izquierdo al cuerpo. Vuelve a la guardia.');};
function renderHistory(){const h=readStore('tyson-history',[]);$('history').replaceChildren();if(!h.length){$('history').textContent='Aún no hay sesiones. La primera empieza hoy.';return;}for(const x of h){let a=document.createElement('article'),left=document.createElement('div'),right=document.createElement('div');left.textContent=new Date(x.date).toLocaleDateString('es-CO',{day:'numeric',month:'short'})+' · '+(x.complete?'COMPLETA':'PARCIAL');const small=document.createElement('small');small.textContent=`${x.rounds}/${x.planned} rounds · ${x.combos} combos indicados`;left.append(document.createElement('br'),small);right.textContent=format(x.work*1000);a.append(left,right);$('history').append(a);}}
$('clearHistory').onclick=()=>{if(confirm('¿Borrar las sesiones guardadas en este dispositivo?')){store('tyson-history',[]);renderHistory();}};
for(const b of document.querySelectorAll('[data-preset]'))b.onclick=()=>{const p={beginner:[1,60,45,4,2],classic:[2,180,60,6,2],quick:[2,120,20,4,2]}[b.dataset.preset];['level','work','rest','rounds','gap'].forEach((k,i)=>$(k).value=p[i]);$('prepare').value=b.dataset.preset==='quick'?60:10;refresh();};
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{$('cue').textContent='Pantalla completa no disponible. Puedes usar la app normalmente.';}};
document.addEventListener('visibilitychange',()=>{if(document.hidden)pause('Sesión pausada al salir de la pantalla. Pulsa Continuar para retomar.');});
document.addEventListener('keydown',e=>{if(e.code==='Space'&&!['INPUT','SELECT','BUTTON','SUMMARY','TEXTAREA'].includes(document.activeElement.tagName)){e.preventDefault();$('start').click();}});
for(const [k,v]of Object.entries(moves)){let a=document.createElement('article'),b=document.createElement('b'),p=document.createElement('p');b.textContent=k+' / '+v[0];p.textContent=v[1];a.append(b,p);$('dictionary').append(a);}
setInterval(()=>{const now=performance.now();if(['idle','done','paused'].includes(clock.state)){previousTick=now;return;}if(clock.state==='work')workMs+=Math.min(now-previousTick,Math.max(0,clock.end-previousTick));previousTick=now;const changed=clock.tick(now);if(changed)stage();if(clock.state==='done')return;$('timer').textContent=format(clock.remaining);const duration=cfg[clock.state==='work'?'work':clock.state==='rest'?'rest':'prepare']*1000;$('progress').style.width=Math.min(100,100*(1-clock.remaining/duration))+'%';$('skip').disabled=clock.state!=='work';if(clock.state==='work'&&!speechBusy&&now>=nextAt)issue();},100);
refresh();renderHistory();
